// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
  baseUrl: string;
};

/**
 * Analysis events schema
 *
 * Analysis events schema
 */
export type AnalysisEventsSchema = {
  id: string;
  step:
    | "extraction"
    | "analysis-part-one"
    | "analysis-part-two"
    | "failed"
    | "completed";
};

export type AppControllerGetHelloData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/api";
};

export type AppControllerGetHelloResponses = {
  200: unknown;
};

export type AnalysisControllerStartAnalyzeData = {
  body?: never;
  path: {
    id: string;
  };
  query?: never;
  url: "/api/analysis/{id}/analyze";
};

export type AnalysisControllerStartAnalyzeResponses = {
  200: unknown;
};

export type AnalysisControllerGetEventsData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/api/analysis/events";
};

export type AnalysisControllerGetEventsResponses = {
  /**
   * SSE stream of analysis
   */
  200: string;
};

export type AnalysisControllerGetEventsResponse =
  AnalysisControllerGetEventsResponses[keyof AnalysisControllerGetEventsResponses];
