// This file is auto-generated by @hey-api/openapi-ts

import { z } from "zod";

/**
 * Analysis events schema
 *
 * Analysis events schema
 */
export const zAnalysisEventsSchema = z.object({
  id: z.string(),
  step: z.enum([
    "extraction",
    "analysis-part-one",
    "analysis-part-two",
    "failed",
    "completed",
  ]),
});

export const zAppControllerGetHelloData = z.object({
  body: z.optional(z.never()),
  path: z.optional(z.never()),
  query: z.optional(z.never()),
});

export const zAnalysisControllerStartAnalyzeData = z.object({
  body: z.optional(z.never()),
  path: z.object({
    id: z.string(),
  }),
  query: z.optional(z.never()),
});

export const zAnalysisControllerGetEventsData = z.object({
  body: z.optional(z.never()),
  path: z.optional(z.never()),
  query: z.optional(z.never()),
});

/**
 * SSE stream of analysis
 */
export const zAnalysisControllerGetEventsResponse = z.string();
